# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortcode',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
