# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20170816_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortcode',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
