# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20170816_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
